spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sb_data_access?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema:
     - classpath:edu_teacher.sql
     - classpath:edu_subject.sql
    initialization-mode: always
